"""c22e8afe69a8a4dd799a53dd34e306fa77041fde

Revision ID: 2c48b36beafd
Revises: 0dc4218438be
Create Date: 2024-07-22 11:17:44.368901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c48b36beafd'
down_revision: Union[str, None] = '0dc4218438be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
