"""84f413b687e3d2a3cc497c7ae8f0e7b7a2efc488

Revision ID: 6ff9e8011314
Revises: 
Create Date: 2024-07-22 10:57:14.753736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ff9e8011314'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_usage')
    op.drop_table('website')
    op.drop_table('api')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api',
    sa.Column('api_id', sa.INTEGER(), server_default=sa.text("nextval('api_api_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('api_id', name='api_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('website',
    sa.Column('website_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('scraped_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_reachable', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('website_id', name='website_pkey')
    )
    op.create_table('api_usage',
    sa.Column('api_usage_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('api_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resonse_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['api_id'], ['api.api_id'], name='api_usage_api_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='api_usage_user_id_fkey'),
    sa.PrimaryKeyConstraint('api_usage_id', name='api_usage_pkey')
    )
    # ### end Alembic commands ###
